### ISSUE TITLE
TypeError: Cannot read property 'aliases' of undefined

### ISSUE THREAD

**Issue by Owned67** [MenuDocs/Discord.JS-Tutorial#1]
const Discord = require("discord.js");
    const config = require("./config.json");
    const fs = require("fs");
    const bot = new Discord.Client();

    bot.commands = new Discord.Collection();
    bot.aliases = new Discord.Collection();

    fs.readdir('./events/', (err, files) => {
      if (err) return console.log(err);
      files.forEach(file => {
    const event = require(`./events/${file}`);
    let eventName = file.split(".")[0];
    console.log(`Loading ${eventName}!`);
    bot.on(eventName, event.bind(null, bot));
      });
    });

    fs.readdir('./commands/', (err, files) => {
    if (err) return console.log(err);
     files.forEach(file => {
    if (!file.endsWith('.js')) return;
    let props = require(`./commands/${file}`);
    let commandName = file.split(".")[0];
    console.log(`Loading ${commandName}!`);
    bot.commands.set(commandName, props);
    props.config.aliases.forEach(alias => {
      bot.aliases.set(alias, props.config.name);
    });
     });
    })
    bot.on('warn', (warn) => console.warn(warn));
    bot.on('error', (error) => console.error(error));
    bot.login(config.token)

**Comment by duncte123** [comment]
Please don't use the issue tracker to receive support but join the discord server instead

https://discord.gg/MgVaazZ
